/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://zwsoxtahezcmpcnztr4uwxr35y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t5zbdt75rbdirg4q5my5vfzwsa",
    "aws_cognito_identity_pool_id": "us-east-1:85eabafb-37bc-457f-88fd-61b5d7b485c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vq260yuos",
    "aws_user_pools_web_client_id": "40fdla6iaumto5e02kp76r15ok",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifyapp9be6252e61094bd89ce22faedcfef41b11000-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
